---
- name: "Set up a Nextcloud server"
  hosts: "{{ target if target is defined else 'nextcloud_servers' }}"
  become: true

  roles:
    # This role has no tasks at all
    - role: galaxy/com.devture.ansible.role.playbook_help

    # This role has no tasks at all
    - role: galaxy/com.devture.ansible.role.systemd_docker_base

    - role: custom/nextcloud_playbook_migration

    - when: nextcloud_playbook_docker_installation_enabled | bool
      role: galaxy/geerlingguy.docker
      vars:
        docker_install_compose: false
      tags:
        - setup-docker
        - setup-all
        - install-docker
        - install-all

    - when: devture_docker_sdk_for_python_installation_enabled | bool
      role: galaxy/com.devture.ansible.role.docker_sdk_for_python
      tags:
        - setup-docker
        - setup-all
        - install-docker
        - install-all

    - when: devture_timesync_installation_enabled | bool
      role: galaxy/com.devture.ansible.role.timesync
      tags:
        - setup-timesync
        - setup-all
        - install-timesync
        - install-all

    - role: custom/base
      tags:
        - setup-all
        - install-all

    # This role exposes various tags (setup-postgres, setup-all, upgrade-postgres, import-postgres, etc.) so we don't tag it here.
    - when: nextcloud_playbook_postgres_installation_enabled | bool
      role: galaxy/com.devture.ansible.role.postgres

    # This role exposes various tags (setup-nextcloud, setup-all, setup-onlyoffice-app, setup-adjust-nextcloud-config, etc.) so we don't tag it here.
    - role: custom/nextcloud_server

    # This role exposes various tags (setup-onlyoffice-document-server, setup-onlyoffice-app, setup-all, etc.) so we don't tag it here.
    - role: custom/nextcloud_onlyoffice_document_server

    - role: custom/nextcloud_collabora_online

    - role: custom/nextcloud_reverse_proxy_companion

    - when: nextcloud_playbook_nginx_proxy_installation_enabled | bool
      role: custom/nextcloud_nginx_proxy

    - when: nextcloud_playbook_traefik_role_enabled | bool
      role: galaxy/com.devture.ansible.role.traefik

    - role: galaxy/com.devture.ansible.role.postgres_backup

    - role: custom/nextcloud_fail2ban

    - when: devture_systemd_service_manager_enabled | bool
      role: galaxy/com.devture.ansible.role.systemd_service_manager

    - role: custom/nextcloud-backup-borg

    # This is pretty much last, because we want it to better serve as a "last known good configuration".
    # See: https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/2217#issuecomment-1301487601
    - when: devture_playbook_state_preserver_enabled | bool
      role: galaxy/com.devture.ansible.role.playbook_state_preserver
      tags:
        - setup-all
        - install-all

    - role: galaxy/com.devture.ansible.role.playbook_runtime_messages
