---
# Project source code URL: https://gitlab.com/etke.cc/borgmatic

nextcloud_backup_borg_enabled: true

nextcloud_backup_borg_base_path: "{{ nextcloud_base_path }}/backup-borg"
nextcloud_backup_borg_config_path: "{{ nextcloud_backup_borg_base_path }}/config"

nextcloud_backup_borg_container_image_self_build: false
nextcloud_backup_borg_docker_repo: "https://gitlab.com/etke.cc/borgmatic"
nextcloud_backup_borg_docker_repo_version: main
nextcloud_backup_borg_docker_src_files_path: "{{ nextcloud_backup_borg_base_path }}/docker-src"

# image and postgres version determined automatically, based on detected postgres server version (if enabled), otherwise latest is used
nextcloud_backup_borg_version: ""
nextcloud_backup_borg_postgres_version: ""
nextcloud_backup_borg_borg_version: 1.2.3
nextcloud_backup_borg_borgmatic_version: 1.7.5
nextcloud_backup_borg_docker_image: "{{ nextcloud_backup_borg_docker_image_name_prefix }}etke.cc/borgmatic:{{ nextcloud_backup_borg_version }}"
nextcloud_backup_borg_docker_image_name_prefix: "{{ 'localhost/' if nextcloud_backup_borg_container_image_self_build else 'registry.gitlab.com/' }}"
nextcloud_backup_borg_docker_image_force_pull: "{{ nextcloud_backup_borg_docker_image.endswith(':latest') or nextcloud_backup_borg_version | default('') == '' }}"

# A list of extra arguments to pass to the container
nextcloud_backup_borg_container_extra_arguments: []

# List of systemd services that matrix-backup-borg.service depends on
nextcloud_backup_borg_systemd_required_services_list: ['docker.service']

# List of systemd services that matrix-backup-borg.service wants
nextcloud_backup_borg_systemd_wanted_services_list: []

# systemd calendar configuration for the backup job
# the actual job may run with a delay (see nextcloud_backup_borg_schedule_randomized_delay_sec)
nextcloud_backup_borg_schedule: "*-*-* 04:00:00"
# the delay with which the systemd timer may run in relation to the `nextcloud_backup_borg_schedule` schedule
nextcloud_backup_borg_schedule_randomized_delay_sec: 2h

# what directories should be added to backup
nextcloud_backup_borg_location_source_directories: []

# postgres db backup
nextcloud_backup_borg_postgresql_enabled: true
nextcloud_backup_borg_supported_postgres_versions: ['12', '13', '14', '15']
nextcloud_backup_borg_postgresql_databases: []
nextcloud_backup_borg_postgresql_databases_hostname: ''
nextcloud_backup_borg_postgresql_databases_username: "nextcloud"
nextcloud_backup_borg_postgresql_databases_password: ""
nextcloud_backup_borg_postgresql_databases_port: 5432

# target repositories
nextcloud_backup_borg_location_repositories: []

# exclude following paths:
nextcloud_backup_borg_location_exclude_patterns: []

# borg encryption mode, only "repokey-*" and "none" are supported
nextcloud_backup_borg_encryption: repokey-blake2

# private ssh key used to connect to the borg repo
nextcloud_backup_borg_ssh_key_private: ""

# allow unencrypted repo access
nextcloud_backup_borg_unknown_unencrypted_repo_access_is_ok: "{{ nextcloud_backup_borg_encryption == 'none' }}"

# borg ssh command with ssh key
nextcloud_backup_borg_storage_ssh_command: ssh -o "StrictHostKeyChecking accept-new" -i /etc/borgmatic.d/sshkey

# compression algorithm
nextcloud_backup_borg_storage_compression: lz4

# archive name format
nextcloud_backup_borg_storage_archive_name_format: nextcloud-{now:%Y-%m-%d-%H%M%S}

# repository passphrase
nextcloud_backup_borg_storage_encryption_passphrase: ""

# retention configuration
nextcloud_backup_borg_retention_keep_hourly: 0
nextcloud_backup_borg_retention_keep_daily: 7
nextcloud_backup_borg_retention_keep_weekly: 4
nextcloud_backup_borg_retention_keep_monthly: 12
nextcloud_backup_borg_retention_keep_yearly: 2

# retention prefix
nextcloud_backup_borg_retention_prefix: nextcloud-

# Default borgmatic configuration template which covers the generic use case.
# You can customize it by controlling the various variables inside it.
#
# For a more advanced customization, you can extend the default (see `nextcloud_backup_borg_configuration_extension_yaml`)
# or completely replace this variable with your own template.
nextcloud_backup_borg_configuration_yaml: "{{ lookup('template', 'templates/config.yaml.j2') }}"

nextcloud_backup_borg_configuration_extension_yaml: |
  # Your custom YAML configuration for borgmatic goes here.
  # This configuration extends the default starting configuration (`nextcloud_borg_configuration_yaml`).
  #
  # You can override individual variables from the default configuration, or introduce new ones.
  #
  # If you need something more special, you can take full control by
  # completely redefining `nextcloud_backup_borg_configuration_yaml`.

nextcloud_backup_borg_configuration_extension: "{{ nextcloud_backup_borg_configuration_extension_yaml | from_yaml if nextcloud_backup_borg_configuration_extension_yaml | from_yaml is mapping else {} }}"

# Holds the final borgmatic configuration (a combination of the default and its extension).
# You most likely don't need to touch this variable. Instead, see `nextcloud_backup_borg_configuration_yaml`.
nextcloud_backup_borg_configuration: "{{ nextcloud_backup_borg_configuration_yaml | from_yaml | combine(nextcloud_backup_borg_configuration_extension, recursive=True) }}"
